### ISSUE TITLE
Brak wyświetlania się płatności ratalnej

### ISSUE THREAD

**Issue by Tomskor** [PayU-EMEA/plugin_prestashop#248]
Witam, po zainstalowaniu i włączeniu opcji rat w module PAYU nie są one widoczne i aktywne na sklepie, jak to naprawić?

**Comment by mfalewicz** [comment]
Czy Raty PayU zostały dodane przez panel menadżera lub przez obsługę klienta? Tzn czy zostały włączone dla danego punktu płatności? Sama instalacja wtyczki nie włącza automatycznie rat, potrzebna jest konfiguracja w panelu https://secure.payu.com/user/start

**Comment by Tomskor** [comment]
@mfalewicz już zostały dodane i działa, niestety problem jest bo po włączeniu modułu w zasadzie możliwości płatności ratalnej strona traci 10-15pkt w google page speed index, czym jest to spowodowane i jak usunąć tą niedogodność? Bo nie ukrywam ze względów SEO uniemożliwia to w ogóle wdrożenie tego rozwiązania. Testowałem włączanie i wyłączanie metod promocji, to jest tylko niestety częściowy problem. Poza tym na stronie głównej nie wyświetla się nic związanego z PayU to dlaczego tak strona główna traci na szybkości?

**Comment by mfalewicz** [comment]
Najpewniej spowodowane jest to dodatkowymi skryptami js zaciąganymi ze stron PayU. W przyszłości planujemy zminimalizować wszystko do jednego pliku, żeby nie traciło na tym SEO

**Comment by Tomskor** [comment]
@mfalewicz jak bardzo odległy jest termin takiego usprawnienia? ponieważ pomimo szczerych chęci nie możemy uruchomić płatności ratalnej na naszym sklepie bo spadamy poniżej 80 punktów w testach google... czy nie mogą te pliki ściągać się np już w koszyku albo podczas składania zamówienia? jest jakakolwiek możliwość zoptymalizowania tego w najbliższym czasie?

**Comment by hakeryk2** [comment]
Również dołączam się do pytania. Nie aktualizuję wtyczki od momentu pojawienia się rat ponieważ nie chcę zasysać tony .js'ów - fajnie by było gdyby można było wybrać również czy chce się w ogóle partycypować w ratach.

**Comment by hakeryk2** [comment]
Ogólnie na 1.6 z OPC od X13 też nie mogę sprawić by te płatności pojawiły się na liście płatności. Wiem, że to nie Wasza sprawa by działało to z zewnętrznymi modułami, ale może jakieś info gdzie tworzy się dodatkowy przycisk by już na liście płatności pojawiła się opcja wyboru rat.

**Comment by mfalewicz** [comment]
@Tomskor & @hakeryk2  - już od jakiegoś czasu odchudziliśmy js-y, sprawdzaliśmy SEO i jest zdecydowanie lepiej. Prośba o potwierdzenie poprawy

**Comment by mfalewicz** [comment]
@Tomskor & @hakeryk2 w obecności braku sprzeciwu, zamykam. W razie problemów prośba o otwarcie nowego zgłoszenia.
