### ISSUE TITLE
error.log legacyClassNames

### ISSUE THREAD

**Issue by reno126** [PayU-EMEA/plugin_prestashop#253]
Gdy logi są włączone , to w error.log jest sporo takich wpisów:

  {16384 runtimeError in .../classes/Tab.php} In line: 342 with message: AdminMarketing is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/.

  {2 runtimeError in .../classes/Media.php} In line: 269 with message: filemtime(): stat failed for... /themes/default/css/theme.css

Czyli w module są cały czas użyte stare nazwy klas, które tylko przypadkiem jeszcze funkcjonują.

**Comment by regdos** [comment]
Te błędy nie pochodzą z naszego modułu.

**Comment by reno126** [comment]
hmm... ok. Ale to czemu pojawiają się w logach modułu PU ?

Pozdrawiam,
Krzysztof Piekacz




czw., 31 sty 2019 o 10:57 Tomasz Regdos <notifications@github.com>
napisał(a):

**Comment by reno126** [comment]
ponawiam temat. Jak to możliwe, że inny moduł pisze do pliku logów PU ??? i to jeszcze po włączeniu zapisywania logów właśnie w module PU ?

**Comment by regdos** [comment]
Proszę o wklejenie całego stacktrace błędu oraz informację czy błąd pojawia podczas działania na frontendzie czy backendzie?

**Comment by reno126** [comment]
ale to jest wszystko co znalazłem z error.log. Te dwa błędy występują jeden po drugim i pojawiają się przy zmianie status PU. Tak więc po dwóch dniach logów mam ich około 200

Drugi błąd jaki zauważyłem to
{16384 runtimeError in /home/glowna/domains/..../public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php} In line: 585 with message: Fetching the "prestashop.core.filter.front_end_object.main" private service or alias is deprecated since Symfony 3.4 and will fail in 4.0. Make it public instead.

On się pojawia przy przekierowaniu do PU (na froncie sklepu)

PS 1.7.4.2 - brak zmian w plikach

**Comment by regdos** [comment]
W najnowszej wersji został poprawiony Logger PayU ponieważ poprzednio miał własną konfigurację handlera błędów i zbierał również błędy z innych modułów Prestashop.
