### ISSUE TITLE
Płatność przy podzielonym zamówieniu

### ISSUE THREAD

**Issue by MarcinBednarz** [PayU-EMEA/plugin_prestashop#255]
W wypadku, gdy zamówienie jest podzielone ze względu na sposób wysyłki moduł PayU bierze tylko pod uwagę część zamówienia, drugie trzeba opłacić osobno. Podzielone zamówienie ma ten sam indeks, ale rożni się numerem ID.
Aby zduplikować należy dodać do koszyka dwa różne produkty, które nie mają wspólnego sposobu wysyłki.

**Comment by regdos** [comment]
Faktycznie występuje taki problem jednak naprawa wymaga sporego nakładu pracy więc nie jesteśmy w stanie określić kiedy problem zostanie rozwiązany.

**Comment by mcmaroon** [comment]
@regdos  Podobijam, ponieważ natrafiłem właśnie na ten sam błąd który opisał Marcin. 
1. W metodzie classes/PaymentModule.php linia 327 prestashop rozbija zamówienie z podziałem na typ przewoźnika
2. W tej samej metodzie linia 722 ustawia currentOrder z którego potem korzysta moduł payu 
3. W efekcie powstają dwa zamówienia a praktycznie losowe przypisywane jest do płatności payu

**Comment by regdos** [comment]
Naprawione od wersji 3.2.0
