### ISSUE TITLE
Błąd 400 przy powrocie z płatności

### ISSUE THREAD

**Issue by ReMiXs** [PayU-EMEA/plugin_prestashop#261]
Przy powrocie z płatności na stronie https://secure.payu.com/hub/ipko/callback/ok
dostaję błąd 

HTTP Status 400 -
Type | Status report
Message |  Description | The request sent by the client was syntactically incorrect ().

Prestashop 1.7.6.0
Jakieś sugestie jak to rozwiązac?

**Comment by regdos** [comment]
To nie jest problem po stronie Prestashop. Po adresie wygląda to na tymczasowy problem z obsługą powrotu z ipko jeszcze po stronie PayU.
