### ISSUE TITLE
Error has occurred: ERROR_VALUE_INVALID: One or more required values are incorrect.

### ISSUE THREAD

**Issue by JurekSIN** [PayU-EMEA/plugin_prestashop#263]
Wtyczka nie wysyła żądania do PayU, wypluwa za to błąd od razu po wybraniu płatności przez PayU (to samo w trybie SandBox):

> Error has occurred: ERROR_VALUE_INVALID: One or more required values are incorrect.

**Bardzo prosimy o pilną pomoc, chcemy zacząć przyjmować płatności, ale już od kilku tygodni czekamy na pomoc supportu.**

![CapturFiles_219](https://user-images.githubusercontent.com/24252068/66627970-a80a2080-ebfd-11e9-97f6-b5dd0449b5b0.png)

Wersja wtyczki: v3.0.21

PrestaShop version: 1.7.5.2
Shop URL: http://chemical-safety.eu/
MySQL version: 5.7.21-20-log
Server information FreeBSD FreeBSD 11.2-RELEASE-p14 #10: Tue Aug 20 21:39:40 CEST 2019 root@pkg11.admin.net.pl:/usr/obj/usr/src/sys/devil amd64
Server software version: Apache/N-G-I-N-X-htaccess-support
PHP version: 7.1.21
Memory limit: 512M
Max execution time: 300
Upload Max File size: 2048M

**Comment by regdos** [comment]
Niesety nie udało mi się zdiagnozować problemu. Dzisiaj do Państwa odezwie się support z prośbą o dodatkowe dane żebyśmy mogli rozwiązać problem.

**Comment by JurekSIN** [comment]
Dziękuję za szybką reakcję. Czekamy na kontakt (sklep@sin.org.pl).

**Comment by kambar** [comment]
Udało się to rozwiązać? Mam ten sam problem, prestashop po angielsku (waluta to złotówki) i się wywala z takim samym błędem, presta 1.6.

**Comment by kambar** [comment]
Jeśli język sklepu to polski wszystko działa ale po angielsku się wywala.

**Comment by JurekSIN** [comment]
Ostatecznie się udało, ale niepamiętamy już jak, pomógł chyba support na tech@payu.pl. Ogólnie to rezygnujemy z Prestashop bo wywala sie wszystko, od platnosci, przez DPD, po friendly urls. Nigdy wiecej prestashopu

**Comment by kambar** [comment]
Dzieki za odpowiedz, no wlasnie reklama na UK idzie od jakiegos czasu a tutaj taka niespodzianka bo PayU nie dziala. Na co sie przerzucacie z presty? Tutaj takie niespodzianki co krok niestety. W nic nie mozna juz wierzyc. Jak cos raz zadziala to nie ma gwarancji ze nastepnym razem tez zadziala ehhh

**Comment by regdos** [comment]
@kambar a jaki jaki masz podany kod języka angielskiego w presta? Jeżeli jest inny niż en to pojawia się błąd nie ma kodu języka np. gb lub uk.

**Comment by kambar** [comment]
Uuu wlasnie jest gb bo cos tam nie dziala w sklepie jak jest en, da sie to jakos obejsc?

**Comment by regdos** [comment]
W PayU operujemy na kodach ISO języków dlatego nie działa gb. W pluginie pobieramy kod iso języka za pomocą Language::getIsoById. Można napisać swoją metodę, która przemapowuje gb na en lub zmienić definicję języka w presta żeby iso było prawidłowe.

**Comment by kambar** [comment]
Wydaje sie ze dziala po zamianie wyzej wymienionego na (Language::getIsoById($this->context->language->id) == 'gb' ? 'en' :Language::getIsoById($this->context->language->id)) we wszystkich miejscach w payu.php oprocz linia 585 wyswietlona ponizej (bo to jest zwrotny url w sklepie i powinno byc lang=gb ? - to pytanie do @regdos, zgadza sie?

$return_array = array(
                    'redirectUri' => urldecode($result->getResponse()->redirectUri.'&lang='.Language::getIsoById($this->context->language->id)),
                    'orderId' => $result->getResponse()->orderId
                );

**Comment by regdos** [comment]
w tym redirectUri też powinno być zmienione choć nie ma to wielkiego znaczenia bo to adres do przekierowania na stronę PayU i jeżeli jest ten lang jet niepoprawny to zostanie zignorowana język pobrany z przeglądarki.

**Comment by kambar** [comment]
Dzieki za odpowiedz!

**Comment by JurekSIN** [comment]
> Dzieki za odpowiedz, no wlasnie reklama na UK idzie od jakiegos czasu a tutaj taka niespodzianka bo PayU nie dziala. Na co sie przerzucacie z presty? Tutaj takie niespodzianki co krok niestety. W nic nie mozna juz wierzyc. Jak cos raz zadziala to nie ma gwarancji ze nastepnym razem tez zadziala ehhh

WooCommerce. Są darmowe wtyczki do wszsytkiego, a płatne pluginy są tanie - nie 150$ za byle co jak do Presty.

**Comment by kambar** [comment]
No dokładnie. Jak zobaczyłem ile byle plugin pierdoła kosztuje to się delikatnie mówiąc kopara opadła. Ale cóż narazie trzeba pchać presta wózek. Niestety nie ode mnie zależało tylko przejęte skądś i teraz zabawy co nie miara.
