### ISSUE TITLE
Nie działa "zapłać ponownie przez PayU"

### ISSUE THREAD

**Issue by lutek** [PayU-EMEA/plugin_prestashop#265]
Nie działa opcja "zapłać ponownie przez PayU" w prestashop 1.7.6.1 po kliknięciu w link pojawia się pusty koszyk.

**Comment by lutek** [comment]
Czy ta opcja będzie działać? Dość często klienci mają problem z przerwaną płatnością, generowanie nowych zamówień miesza w rezerwacjach produktów.

**Comment by hakeryk2** [comment]
Działa dla zalogowanych, nie działa dla gości. W poprzednich wersjach jeszcze jakoś to ominąłem, teraz już nie umiem.

**Comment by regdos** [comment]
@lutek czy używasz najnowszej wersji pluginu?
Sama opcja ponownej płatności działa i dla zalogowanych i dla gości. Przed chwilą to testowałem.
W przypadku ponownego płacenia nie następuje przejście przez koszyk. 

Co do samego mechanizmu ponownego płacenia wiemy, że nie jest on idelany ponieważ aktualnie można ponowić płatność tylko gdy poprzednia jest anulowana żeby nie doszło do sytuacji podwójnego pobrania środków od kupującego.

**Comment by hakeryk2** [comment]
W 1.6 też jak testuję sam na localhoście to działa, ale dlatego, że mam coś w koszyku, nie wiem dlaczego. Klient jak złoży zamówienie i ma pusty koszyk to przenosi go pustej podstrony koszyka l tyle. Wystarczy, że ma w nim cokolwiek i dopiero przekierowanie działa - nie mam pojęcia dlaczego.

**Comment by icecrypt** [comment]
Używam Presty 1.6 oraz PayU 3.1.3 i również widzę ten problem. Jeśli podczas realizacji zamówienia i wyborze np. płatności Blik, anuluję proces i wrócę na stronę, to otrzymam komunikat "Status zamówienia xxx - Płatność PayU rozpoczęta", po przejściu w Szczegóły zamówienia, status płatności PayU to już "anulowana". Kliknięcie w "Zapłać ponownie przez PayU" spowoduje przekierowanie do kasy (mam OPC więc url /szybkie-zakupy), ale wyświetli się błąd "Twój koszyk jest pusty."

**Comment by regdos** [comment]
W pluginie 3.2.0 został wprowadzony nowy mechanizm ponawiania.
