### ISSUE TITLE
Wywalcie to 1DAFEC ze swojego widżetu...

### ISSUE THREAD

**Issue by PrestaShark** [PayU-EMEA/plugin_prestashop#271]
Pięknie proszę...

**Comment by regdos** [comment]
Nie ma takiego koloru użytego w widgecie. Proszę o jakiegoś screena.

**Comment by PrestaShark** [comment]
https://static.payu.com/res/v2/widget-products-installments.js 

linkToInstallmentDetails.setAttribute('style', 'font-weight:normal;text-decoration:underline;color:#1DAFEC;cursor:pointer;');

**Comment by jakub-gardo-payu** [comment]
Ten fragment kodu jest wspódzielony w wielu miejscach, więc poprawka tego i przetestowanie może trochę trwać.

Póki co proponuję obejście problemu poprzez dodanie customowych styli:

```
.payu-widget-installments-mini {
    font-weight: normal!important;
    text-decoration: underline!important;
    color: #000000!important;
    cursor: pointer!important;
}
```

**Comment by jakub-gardo-payu** [comment]
Zgłoszenie nie zostanie zrealizowane, opis stylowania dostępny pod [tym linkiem](https://developers.payu.com/pl/installments.html#installment_widget_visualization)
