### ISSUE TITLE
Fałszywy komunikat o nadpłacie

### ISSUE THREAD

**Issue by Cestis** [PayU-EMEA/plugin_prestashop#272]
W panelu klienta PayU nie ma nadpłaty, jedynie pełna kwota. W panelu PrestaShop wygląda to tak:

![image](https://user-images.githubusercontent.com/3482915/80592953-9add4380-8a20-11ea-9e7b-ecd7f51a2f33.png)

![image](https://user-images.githubusercontent.com/3482915/80592983-a7619c00-8a20-11ea-9f24-3e5f38dd1825.png)

![image](https://user-images.githubusercontent.com/3482915/80592997-acbee680-8a20-11ea-830f-8fe5a96571dc.png)

**Comment by regdos** [comment]
Czy ten problem występuje we wszystkich zamówieniach? 
Czy jest od zawsze czy pojawił się w określonym czasie?

**Comment by Cestis** [comment]
nie, to był jednorazowy przypadek

**Comment by Notsa** [comment]
U mnie również się to powtarza, sporadycznie ale robi problemy.
![image](https://user-images.githubusercontent.com/7301001/86924791-38937400-c130-11ea-92d0-3219925bfedf.png)

**Comment by icecrypt** [comment]
Na Preście 1.6 wraz z modułem 3.1.3 dziś zdarzyło mi się to samo. Wcześniej podobny problem pojawił się około 3 miesiące temu.
