### ISSUE TITLE
Nie zmieniają się statusy zamówień

### ISSUE THREAD

**Issue by modzel64** [PayU-EMEA/plugin_prestashop#274]
W prestashop 1.6.1.5 nie zmieniają się statusy zamówień. Wszsytkie zamówienia złożone przez klientów otrymują status "Płatność PayU rozpoczęta", i nie zmienia się on po opłaceniu zamówienia. Wersja aktualnie zainstalowanego modułu: 3.1.6

**Comment by Triloworld** [comment]
Oczywiście jest to blokada odpowiedzi z strony PayU. W Cloudflare jest to spowodowane opcją integracji przeglądarki 
By otrzymać zwrot należy sprawdzić czy "\notification" i User Agent jest przepuszczany przez filtr.
Mi pomogło dodanie w `Rules` wpis: 
```
https://example.com/*/module/payu/*
Browser Integrity Check: Off, Always Online: Off, Cache Level: Bypass
```

**Comment by regdos** [comment]
Poprzez panel PayU można sprawdzić jaka jest odpowiedź na notyfikację i w większości jest to związane z Cloudflare ponieważ notyfikacja to komunikacja typu server->server a Cloudflare przy włączonej opcji Browser Integrity Chceck sprawdza czy User Agent jest z przeglądarki.

**Comment by Triloworld** [comment]
Jedynie nadmienię że jeśli nie ma Pan @modzel64 CloudFlare to firewall lub inne mechanizmy na serwerze blokują informację zwrotną (proxy, firewall, blokada IP, blokada User Agent) i nie jest to spowodowane błędem modułu. Zgodnie z tym co pisze @regdos należy najpierw sprawdzić w panelu przyczynę i jaka jest odpowiedź z serwera zanim uzna się błąd modułu.

**Comment by hakeryk2** [comment]
W panelu Cloudflare należy po prostu dodać IP PayU jako "allow" w Firewall -> Tools -> i dodać jako "Allow" te adresy:
185.68.12.10, 185.68.12.11, 185.68.12.12, 185.68.12.26, 185.68.12.27, 185.68.12.28
