### ISSUE TITLE
Brak przekierowania do płatności po wybraniu metody

### ISSUE THREAD

**Issue by patrys666** [PayU-EMEA/plugin_prestashop#275]
Problem polega na tym, że po wypełnieniu formularza dostawy, wybrania metody dostawy oraz metody płatności Payu i kliknięciu kup teraz przechodzi na stronę module/payu/payment
a tam wyświetla się komunikat:

> Proszę wybrać metodę płatności

Poniżej są tylko dwa przyciski. Wybór innej metody płatności oraz potwierdzam zamówienie i płacę. Po wciśnięciu drugiego strona się po prostu odświeża.
Wersja PS: 1.6.1.23

**Comment by zgredoslav** [comment]
Mam ten sam błąd na 1.6.1.17.

Ramka płatności payu w tej wersji jest w osobnej ''podtabelce'', kompletnie nie działa w niej link - klikasz i nic, choć przekierowanie jest widoczne po najeździe myszką.

Po stworzeniu przekierowania na /module/payu/payment ręcznie, strona przeładowuje po kliknięciu do wyboru płatności. Wybierasz, zatwierdzasz i znowu prosi o wybór płatności - i tak w kółko.

Pisałem na pomoc@payu.pl kilka tygodni temu i nikt się nie odzywa. Wspaniałe wsparcie.
