### ISSUE TITLE
Blik jako osobna metoda płatności

### ISSUE THREAD

**Issue by futurowebpl** [PayU-EMEA/plugin_prestashop#276]
Witam, 

Prośba aby zaimplementować taką funkcjonalność w module,

Powinna być możliwość wyświetlenia BLIKa jako osobnej metody platności - dokładnie jak osobna metoda płatność kartą.

W zasadzie można się bawić w customowe przeróbki ale to powinno zostać wdrożone w natywnej wersji modułu.

**Comment by rzuf666** [comment]
Popieram, na pewno powinna być opcja na wyodrębnienie BLIKa jako oddzielna metoda płatności tak jak to jest możliwe z kartą płatniczą. BLIK jest obecnie najczęściej wybierany. Nasi klienci, którym realizujemy sklepy na PrestaShop pożądają takiej funkcji i często o to pytają.

Na pewno nie wiąże się to też z dużą ilością programowania, ponieważ wszystko co potrzebne do tego już jest w module. Możliwe jest  na tą chwilę samodzielne przerobienie modułu i wykorzystanie odrębnej metody karty by kierowała bezpośrednio na BLIKa:

W pliku payu.php w linijce 744 można zmienić 'payMethod' => 'c' na 'payMethod' => 'blik' (oczywiście wymagana jest też zmiana nazwy formy płatności oraz ikon kart na blika).

Następnym krokiem powinna być większa możliwość ręcznego ustawiania które formy płatności powinny się wyświetlać bezpośrednio w metodach płatności Presty w 3 kroku. Konkurencja nie śpi i inne bramki płatnicze dla PrestaShop mają taką możliwość.

**Comment by regdos** [comment]
Zmiana została wprowadzona, po wprowadzeniu innych poprawek wydamy nową wersję.

**Comment by staszek-arbuz** [comment]
Czy nowa wersja zawiera już możliwość ustawienia wybranych płatności w koszyku Presty ?
