### ISSUE TITLE
Niezgodność z wersją Prestashop 1.7.7.0+

### ISSUE THREAD

**Issue by ProteanCode** [PayU-EMEA/plugin_prestashop#277]
Plugin nie działa w pełni z wersją Prestashop 1.7.7.0+

Pierwsze problemy jakie widzę występują ze zwrotem (refundem). Po prostu nie da się go wykonać tą wtyczką.

Przyczyną jest inne generowanie adresów URL przez nowe wydanie. 

Aktualnie wchodząc w zamówienie nasz adres URL wygląda mniej więcej tak:
`https://example.com/admin12345/index.php/sell/orders/666/view?_token=mysupersecrettoken`

Podczas gdy poprzednia wersja posiadała w linku parametry **id_order** oraz **vieworder**

`https://example.com/admin12345/index.php?controller=AdminOrders&id_order=666&token=mysupersecrettoken&vieworder=1`

Kod funkcji `hookBackOfficeHeader` zawiera następujący fragment:

```
    $vieworder = Tools::getValue('vieworder');
    $id_order = Tools::getValue('id_order');

    $refundable = false;

    if ($vieworder !== false && $id_order !== false) {
        $order = new Order($id_order);
        $order_payment = $this->getLastOrderPaymentByOrderId($id_order);

        if ($order->module === 'payu' && $order_payment['status'] === OpenPayuOrderStatus::STATUS_COMPLETED) {
            $refundable = true;
        }
    }
```

W takiej sytuacji refundy po prostu nie mogą działać.

Problemów z tym związanych może być pewnie dużo więcej

**Comment by regdos** [comment]
@ProteanCode Proszę o aktualizację pluginy do wersji 3.1.8 gdzie ten problem został rozwiązany. 

Zamieniło się umiejscownie formularza zlecenia zwrotu jest on teraz w sekcji "Zamówienia w PayU"
