### ISSUE TITLE
Ograniczenia przewoźnika

### ISSUE THREAD

**Issue by soktherat** [PayU-EMEA/plugin_prestashop#280]
Nie działają ustawienia Ograniczenia przewoźnika w Preferencjach płatności.
Metoda płatności jest wyłączona (dla np wysyłki za pobraniem) a jest dostępna na stronie zamówienia.

**Comment by regdos** [comment]
Nie używa Pan jakiejś nietypowego szablonu albo pluginu do zamówienia? Bo sprawdziliśmy taką konfigurację  po swojej stronie i jest ok.

**Comment by Triloworld** [comment]
Potwierdzam: nie działają filtry dla tego modułu.
Ograniczenie per waluta jak i per przewoźnik nie jest brany pod uwagę.
Dla testów płatność czekiem (moduł: ps_checkpayment) była tak samo ograniczona i prawidłowo jest ukrywana.

Prestashop 1.7.7.2

**Comment by Triloworld** [comment]
Znaleziony powód: hookDisplayPaymentEU

Rozwiązanie:
```php
    public function hookDisplayPaymentEU()
    {

        if (!$this->active) {
            return;
        }
	 
        $cart = $this->context->cart;
        if (!$this->checkCurrency($cart)) {
            return array(); //Don't revert to null - https://github.com/PrestaShop/PrestaShop/issues/18229
        }

        $payment_options = array(
            'cta_text' => $this->l('Payment by card or bank transfer via PayU'),
            'logo' => $this->getPayuLogo(),
            'action' => $this->context->link->getModuleLink('payu', 'payment')
        );

        return $payment_options;
    }
```

**Comment by Triloworld** [comment]
Dla testów: Język ENG, waluta GBP i PayU wyłączone na tą walutę
Może być powiązane z : https://github.com/PayU-EMEA/plugin_prestashop/issues/250

**Comment by dbartelmus** [comment]
Ograniczenia przewoźników w relacji do metody płatności ustawiane w Prestashop 1.7 (Płatności -> Preferencje -> Ograniczenia przewoźnika) nie działają poprawnie.
Co więcej pytanie o domyślny szablon jest trochę bezpodstawne gdyż nie powinno mieć to żadnego znaczenia przy ukrywaniu metod w korelacji do w/w ustawień.

Rzecz pozostaje nierozwiązana, odbiór osobisty lub paczka pobraniowa będzie również pokazywała metodę płatności "PayU" - być może to celowy zabieg zwiększający konwersję z prowizji... ;)

**Comment by regdos** [comment]
Ograniczenie metody płatności w zależności od jej dostępności lub waluty jest zawarta w implementacji odpowiedniego hook-a. Hook `displayPaymentEU` dotyczył tylko Presta 1.6 i faktycznie nie miał tego sprawdzania. Dla Presta 1.7 jest takie sprawdzanie. 

W przypadku ograniczenia związanego z metodą wysyłki sprawdzaniem tego zajmuje się Presta już na poziomie pobierania dostępnych modułów z bazy danych więc nie ma możliwości, że w pluginie tego nie respektować bo w ogóle nie zostanie wywołany ten kod. 

Ponownie wykonaliśmy testy (tak samo jak pisałem w 2021 roku) i potwierdzamy, że wszystko działa. 

Podsumowując:
Presta 1.6 (hook `displayPaymentEU`) - działa ograniczenie per przewoźnik,  nie działa ograniczenie per waluta (poprawimy)
Presta 1.6 - działa ograniczenie per przewoźnik i  działa ograniczenie per waluta

@dbartelmus nie wiem jaka jest przyczyna takiego zachowania - może cache (choć hooki dotyczące metod płatności są wyłączone z cache), natomiast chętnie sprawdzimy z czego wynika ten problem.
Faktycznie w przypadku Presta 1.7 szablon nie ma znaczenia bo on otrzymuje listę płatności zgodną z regułami, natomiast w przypadku Presta 1.6 i np. modułu OPC wszystko jest możliwe całkowicie podmienia implementację Presty procesu zakupowego.

**Comment by dbartelmus** [comment]
@regdos Dzięki za analizę. Korzystamy z 1.7 na dosyć dużym sklepie, nie ma implementacji OPC - reguły z 1.7 nie respektują PayU. Możemy się umówić na testy, wpuszczę do zaplecza i kodu. Ja osobiście nie analizowałem, ale chwile możemy na to poświęcić, będę wdzięczny:  hello@panther.software

**Comment by regdos** [comment]
@dbartelmus Problemem były podpięte zaczepy. Wygląda, że była przeprowadzana aktualizacja Presty 1.6 na 1.7 ponieważ był zapięty zaczep `displayPaymentEU` (z Presta 1.6) oraz `paymentOptions` (z Presta 1.7) a podczas wyświetlania metod są brane z obu zaczepów. 
Odpiąłem zaczep `displayPaymentEU` i jest teraz poprawnie. Natomiast warto jest kompleksowo zaktualizować zaczepy poprzez odinstalowanie i zainstalowanie pluginu, natomiast z tym jest problem, ponieważ występuje błąd przy odinstalowaniu. Należy w tabeli `ps_hook_module` sprawdzić dla pluginu PayU (id_module wziętego z tabeli `ps_module`) jakie są id_hook i jeżeli brak jest takiego hook-a w tabeli `ps_hook` to usunąć krotkę z  `ps_hook_module`
Widzę, że moduł `stripe` cały pojawia się przy pobraniu.

**Comment by dbartelmus** [comment]
Tak, była aktualizacja z 1.6 do 1.7. Dziękuje za analizę.DAMIAN BARTELMUSIT Specialist+48 PANTHER 00 (+48726843700)www.panther.softwareWiadomość napisana przez Tomasz Regdos ***@***.***> w dniu 21.12.2022, o godz. 11:55:﻿
@dbartelmus Problemem były podpięte zaczepy. Wygląda, że była przeprowadzana aktualizacja Presty 1.6 na 1.7 ponieważ był zapięty zaczep displayPaymentEU (z Presta 1.6) oraz paymentOptions (z Presta 1.7) a podczas wyświetlania metod są brane z obu zaczepów.
Odpiąłem zaczep displayPaymentEU i jest teraz poprawnie. Natomiast warto jest kompleksowo zaktualizować zaczepy poprzez odinstalowanie i zainstalowanie pluginu, natomiast z tym jest problem, ponieważ występuje błąd przy odinstalowaniu. Należy w tabeli ps_hook_module sprawdzić dla pluginu PayU (id_module wziętego z tabeli ps_module) jakie są id_hook i jeżeli brak jest takiego hook-a w tabeli ps_hook to usunąć krotkę z  ps_hook_module
Widzę, że moduł stripe cały pojawia się przy pobraniu.
