### ISSUE TITLE
Logowanie błędów

### ISSUE THREAD

**Issue by Triloworld** [PayU-EMEA/plugin_prestashop#281]
Poważny błąd w:
https://github.com/PayU-EMEA/plugin_prestashop/blob/b975ad08691766d09ff57f3272944012561a9b6d/payu/tools/SimplePayuLogger/SimplePayuLogger.php#L4

Należy wybrać jedną z zmian by ten problem rozwiązać:
- dodać dokumentację o włączeniu w tym miejscu debugowania jeśli tak ma pozostać
- dodać przełącznik w panelu
- zmienić na zmienną _PS_MODE_DEV_ dzięki czemu unikniemy przełącznika, wystarczy też poinformować że debugowanie zamówień włącza się w trybie developerskim

W tej chwili sporo czasu każdy może tracić na poszukiwanie tego przełącznika w celu debugowania modułu na swoim sklepie.
To problem który wymaga potwierdzenia która zmiana jest najkorzystniejsza i udokumentowanie.

**Comment by regdos** [comment]
@Triloworld  Wrzuciliśmy poprawkę. 
* wpisy do logów są automatycznie robione gdy sklep jest w trybie debugowania
* zmienione zostało umiejscowienie logów na katalog `var/log`, który jest zabezpieczony przed odczytem z sieci
* kod został wyczyszczony i nie przechwytujemy już błędów nie związanych z pluginem  
* plik README został rozszerzony o te informacje

**Comment by Triloworld** [comment]
Dziękuję serdecznie. Również pozwoli by przyszłe zadania były lepiej opisane.
