### ISSUE TITLE
Obsługa: ERROR_INCONSISTENT_CURRENCIES

### ISSUE THREAD

**Issue by Triloworld** [PayU-EMEA/plugin_prestashop#282]
Nagłówek ten informuje o nieobsługiwanej walucie.
POS dla waluty EUR jest z sandboxa i nie przechodzi możliwość zakupu.
Błąd jest typu nieobsłużonego "Exception" przez moduł i wymaga poprawki.

Brak informacji jak mogę podać "EUR" jako walutę w której jest produkt a w której także klient płaci.
Brak testu jednostkowego tego problemu w używanej bibliotece. 
Brak dokumentacji na temat przyjmowanych walut i konfiguracji Prestashopa.

**Comment by regdos** [comment]
Informacja o walutach znajduje się w opisie pluginu - https://github.com/PayU-EMEA/plugin_prestashop#wielowalutowo%C5%9B%C4%87
W panelu Prestashop należy dodać waluty, które chcemy obsługiwać. W konfiguracji pluginu pojawią się  pola do wpisania konfiguracji POS-a dla każdej z walut dodanej w Prestashop.

**Comment by Triloworld** [comment]
Zgodnie z tym dokumentem: https://developers.payu.com/pl/overview.html
POS jest jeden dla wielu punktów. Pytanie więc czy mam tworzyć konto w sandbox? Bo tak uczyniłem i błąd ten sam.
Można by dodać info że to na produkcji działa jedynie i otwartych rachunków w innych walutach? No nie mam jak tego sprawdzić właśnie z powodu tego że mam błąd z API bez dokumentacji na czym polega (teraz nawet ten issue będzie nakierowywał o co chodzi)

**Comment by regdos** [comment]
Ma Pan rację na podanej stronie nie jest jasno wskazane, że testowy punkt płatności jest w walucie PLN. 
Na sandbox jest możliwośc testowania innych walut niz PLN. 
Proszę o kontakt z PayU poprzez formularz na stronie https://poland.payu.com/pomoc/ - Sprzedaję z PayU   / guzik "Zadaj pytanie" / Temat "inny".

W treści proszę napisać, że potrzebuje Pan sklep w EUR na środowisku Sandbox i proszę podać ID Firmy, którą Pan założył na Sandbox.

**Comment by Triloworld** [comment]
Po odpowiedzi z ich strony i odblokowaniu takiej opcji na sandbox, będzie mi miło muc dodać pull request z aktualizacją w readme o tym przypadku i co należy robić.
Poprosiłem by inne waluty w publicznym POS były odblokowane. Dodam tutaj informacje jakie jest oficjalne stanowisko w tej sprawie.

**Comment by Triloworld** [comment]
Potwierdzam: zostało to włączone przez obsługę na żądanie.
Oficjalnie prowadzą wdrożenie tego na publicznym sandbox. Dodam pull request z informacją o tym błędzie i czego dotyczy jako że jest z oficjalnego API i odnosi się do wymaganej konfiguracji od strony developera i serwisu payu aniżeli modułu (nie ma związku z modułem, działa wszystko prawidłowo)

**Comment by Triloworld** [comment]
Zamykam task. Pozostawiam pull request z aktualizacją dokumentacji. Proszę o włączenie jako że błąd jest oznaczony a szczegółów brak. Ta informacja będzie pozwalała w przyszłości innym znaleść rozwiązanie gdyż nie udało się nigdzie, w żadnej oficjalnej dokumentacji, znaleść opis błędu i co należy wykonać. 

Dziękuję serdecznie @regdos za pomoc.

**Comment by Triloworld** [comment]
Dopytałem: "Moge potwierdzić, że wkrótce w dokumentacji mają pojawić się dwa najczęściej testowane POSy na środowisku Sandbox (oczywiście poza PLN) w walutach CZK oraz EUR. " a pozostałe po kontakcie z obsługą są włączane na sandbox
