### ISSUE TITLE
Błędna kwota do zapłaty przy produktach 2 różnych producentów i brak aktualizacji statusu

### ISSUE THREAD

**Issue by adrisiem** [PayU-EMEA/plugin_prestashop#288]
Witam,

Dla Presta 1.6 korzystajac od kilku lat z modulu PayU 3.02 mielismy od zawsze problem dotyczacy braku aktualizacji statusu zamowienia w sytuacji gdy klient w ramach jednego zamowienia zakupil produkty roznych producentow. Wtedy zamowienie bylo dzielone na Presta 1.6 na dwa rozne i platnosc PayU przechodzila za calosc, a status aktualizowal (zaplacono) aktualizowl sie tylko dla jednego zamowienia - drugi mial status 'platnosc oczekujaca'. Dopiero po recznym sprawdzeniu statusu transakcji na payu zmienialismy go recznie. 

Chcialem wyeliminowac ten problem i zaktualizowalem modul do najnowszej wersji tj. 3.1.1 i teraz jest jeszcze gorzej:
- mianowicie obecnie jesli dodam do koszyka produkty 2 roznych producentow, to caly czas kwota do zaplaty jest w porzadku, ale po przekierowaniu do payu (np. bllik lub bank online) pokazuje kwote do zaplaty tylko dla jednego z nich. Co najgorsze, po zaplaceniu tej zanizonej kwoty tylko dla 1 produktu, na maila przychodzi informacja ze wszystkie produkty zzostaly oplacone.

**Comment by adrisiem** [comment]
Do samego końca na naszej stronie kwota pokazuje się prawidłową (sumuje produkty różnych producentów), a po przekierowaniu na payu do banku / blik / płatności karta jest kwota tylko za jeden produkt, pierwszego producenta. 

Próbowałem wgrać starsza wersje 3.1.5 i dalej to samo. Odinstalowałem i zainstalowałem wszystko od nowa - to samo.

**Comment by regdos** [comment]
Taki produkt występował w przypadku produktów z więcej niż jednego magazynu. Od wersji 3.2.0 problem ten został rozwiązany.
