### ISSUE TITLE
Listing możliwych płatności jest nieprawidłowy

### ISSUE THREAD

**Issue by pafoscan** [PayU-EMEA/plugin_prestashop#290]
Cześć,

Listing płatności PayU u mnie wygląda tak:
![image](https://user-images.githubusercontent.com/84130353/124261112-b6664180-db30-11eb-8d0b-752675956a7b.png)

Czy ktoś wie czy to wynika z błędu wtyczki czy może z czegoś innego?

**Comment by regdos** [comment]
@pafoscan wygląda na problem z CSS-ami, proszę podać adres strony żebyśmy mogli to sprawdzić.

**Comment by pafoscan** [comment]
Wersja testowa naszego serwisu (tutaj jest włączona wtyczka PayU):
https://pafonew.dkonto.pl/

**Comment by regdos** [comment]
@pafoscan mają Państwo włączone CCC czyli łączenie i cachowanie css-ów i js-ów i wygląda, że zawartosć zasobów PayU nie została dodana do plików wynikowych. Proszę skorzystać z guzika "Wyczyść pamięć podręczną" zanjdującego się w:  Zaawansowane /  Wydajność

**Comment by regdos** [comment]
Widziałem na Państwa stronie, że wszystko jest poprawnie wyświetlone więc zamykam.
