### ISSUE TITLE
Zwrot środków poprzez panel Prestashop 1.7 PAYU

### ISSUE THREAD

**Issue by adamj240** [PayU-EMEA/plugin_prestashop#291]
Była opcja w 1.6 Prestashop po kliknięciu w zwrot, aby zwrócić  całość lub część środków na konto klienta. Bardzo pomagało to obsłudze zwrotów, teraz testuję najnowszą wersję 1.7 presty i waszego Plugin i nie widzę możliwości zwrotu poprzez panel presty 1.7. Czy została  ta funkcja "wycięta" - lub jest w innym miejscu w 1.7?

**Comment by regdos** [comment]
W związku ze zmianami jakie zaszły w Presta od wersji  1.7.7.0 zmieniło się umiejscownie formularza zlecenia zwrotu i jest on teraz w sekcji "Zamówienia w PayU"

**Comment by adamj240** [comment]
Ok, widzałem tą sekcję w zamówieniu. Mimo wszystko po zmianach nawet statusów kolumna akcja jest zawsze pusta. Czy muszę coś w zamówieniu ustawić, aby pojawił się button do akcji?
Widok jak w linku [https://2beecomerce.pl/payu.jpg](https://2beecomerce.pl/payu.jpg)

**Comment by regdos** [comment]
@adamj240  Opcja zwrotu jest dostępna po tą tabelką - https://nimb.ws/FSMCbK  i powinna być dostępna u Pana bo status zamówienia w PayU jest COMPLETED

**Comment by patrykdana** [comment]
> @adamj240 Opcja zwrotu jest dostępna po tą tabelką - https://nimb.ws/FSMCbK i powinna być dostępna u Pana bo status zamówienia w PayU jest COMPLETED

Dobry wieczór, a co jeśli nie jest dostępna? W moim panelu nie jest. Aby wykonać zwrot za każdym razem muszę logować się do PayU.

**Comment by regdos** [comment]
Jak jest niedostępna to trzeba sprawdzić dlaczego. Jeżeli chciałby Pan żebyśmy to sprawdzili to proszę o kontakt ze wsparciem PayU powołując się na to zgłoszenie.

**Comment by regdos** [comment]
Po wyjaśnieniu sprawy ze wsparciem należało zaktualizować plugin.

**Comment by patrykdana** [comment]
Tak jest. Dziękuje za pomoc!

W dniu pon., 8.11.2021 o 11:37 Tomasz Regdos ***@***.***>
napisał(a):
