### ISSUE TITLE
Aktualizacja treści względem wymagań UE

### ISSUE THREAD

**Issue by Triloworld** [PayU-EMEA/plugin_prestashop#293]
W związku z aktualizacjami EU w sprawie polityki prywatności proponuję uaktualnić istniejącą treść i dodać wymagane formuły zgodnie z podanymi oficjalnymi informacjami: https://developers.payu.com/en/restapi.html#transparent_compliance

Dla "Data privacy policy":
W tej chwili ten plik ma nieaktualne treści i brak tłumaczeń dla wielu wspieranych języków: https://github.com/PayU-EMEA/plugin_prestashop/blob/48e04fb82dd6d5d81917946e11c3ae67a68064e6/payu/views/templates/front/conditions17.tpl

Dla "PayU Payment Terms":
Dodatkowo tłumaczenie nie uwzględnia by część w cudzysłowiu była linkiem (ani nie jest 1:1 mimo to chodzi bardziej o link do regulaminu): https://github.com/PayU-EMEA/plugin_prestashop/blob/48e04fb82dd6d5d81917946e11c3ae67a68064e6/payu/translations/pl.php#L66

Należały dodać wszystkie dostępne tłumaczenia formułek które legalizują działanie i wymaganie ich w dla odpowiedniego języka. Traktuję ten "issue" jako audyt brakujących treści względem wymaganych po czystej instalacji modułu. Po instalacji nie pojawił mi się checkbox wymagający akceptacji regulaminu ani dodatkowych informacji o przetwarzaniu płatności przez PayU

**Comment by regdos** [comment]
W najnowszej wersji pluginu 3.2.0 zostało to wykonane.
