### ISSUE TITLE
Informacja o wersji pluginu w tytule płatności

### ISSUE THREAD

**Issue by LukaszMalekBH** [PayU-EMEA/plugin_prestashop#295]
Witam, 

dzisiaj klient zgłosił nam informację o wersji pluginu w tytule płatności jako informację sugerującą wyłudzenie płatności. 

Można to jakoś wyłączyć? Zmienić? Chodzi o plugin do PrestaShop 1.7.2.

![image](https://user-images.githubusercontent.com/90331612/137694172-fccaeeef-2995-489f-b5f9-2c05f00e11ba.png)

**Comment by regdos** [comment]
Wersja pluginu 3.0.8 pochodzi z 2018 roku. Eksponowanie wersji zostało usunięte w 3.0.9. Wystarczy zaktualizować plugin do najnowszej wersji i problem zostanie rozwiązany.
