### ISSUE TITLE
Jak nie mam nic w koszyku to nie da się ponowić płatności.

### ISSUE THREAD

**Issue by lobowilk** [PayU-EMEA/plugin_prestashop#296]
Jak to skonfigurować żeby dało się zapłacić za zamówienie po anulowaniu płatności.

**Comment by Triloworld** [comment]
Są 4 sposoby by klient ponownie zapłacił po dokonaniu zamówienia ale przerwanej płatności:
1. za pomocą linku modułem zewn. płatnym (https://prestadev.pl/pl/moduly-prestashop/moduly-platnosci/payu-link-do-platnosci.html)
2. na stronie zamówienia w panelu klienta opcja wykonania płatności (https://github.com/PayU-EMEA/plugin_prestashop#ponowienie-p%C5%82atno%C5%9Bci)
3. za pomocą wykonania tego samego zamówienia (z panelu administratora lub na stronie zamówienia jako ponowne zamówienie)
4. Ręczne przekazanie linku w panelu do klienta (wiadomość wysyłana jest mailem) - **ta opcja nie jest dostępna** i zapytanie poszło do wsparcia. Dam znać czy są zmiany w tej kwestii. Uaktualnię dokumentację jeśli się pojawi też taka forma.

W tej chwili próbujemy wdrożyć sposób nr. 2, też nam nie działa i testujemy co jest przyczyną - prawdopodobnie ustawione statusy są inne niż powinny być.

Testujemy na Prestashop 1.7.0.0, najnowsza wersja wtyczki, standardowy checkout krokowy z modyfikacjami kroków i wyglądu.

**Comment by regdos** [comment]
Wkrótce jako PayU rozpoczniemy prace związane z aktualizacją wtyczki, która umożliwi m.in. ponawianie płatności bez wymaganego statusu CANCELED. Zakończenie prac i publikacja nowej wersji planowana jest na początek kwietnia 2022r.

**Comment by lobowilk** [comment]
Niestety wersja 2 nie działa.
Link do ponowienia płatności przekierowuje do głównej strony sklepu.

**Comment by regdos** [comment]
Od wersji 3.2.0 funkcjonuje nowy system ponowień, który jest wolny od tego błędu.
