### ISSUE TITLE
Link do ponownej płatności w mailu dla konta gościa

### ISSUE THREAD

**Issue by mielcarp** [PayU-EMEA/plugin_prestashop#302]
Przesyłam propozycje rozwiązania do ponownej płatności w mailu jako gość.

Kod obecny:

    public function hookActionGetExtraMailTemplateVars(array &$params)
    {
        if($this->repaymentEnabled() && $params['template'] == 'order_conf') {
            $id_order = false;
            if($this->is17()){
                $id_order = $params['template_vars']['{id_order}'];
            }
            else{
                $sql = 'SELECT id_order FROM ' . _DB_PREFIX_ . 'orders WHERE reference="' . $params['template_vars']['{order_name}'] . '" limit 1';
                $result = Db::getInstance()->ExecuteS($sql);
                $id_order = $result[0]['id_order'];
            }
            $params['extra_template_vars']['{payment}'] = 'PayU, <a href="' . $this->context->link->getPageLink('index',true) .'index.php?controller=order-detail&id_order=' . $id_order . '#repayment">' . $this->l('Repay by PayU') . '</a>';
        }
    }

kod po zmianach:

    public function hookActionGetExtraMailTemplateVars(array &$params)
    {
        if($this->repaymentEnabled() && $params['template'] == 'order_conf') {
            $id_order = false;
            if($this->is17()){
                $id_order = $params['template_vars']['{id_order}'];
            }
            else{
                $sql = 'SELECT id_order FROM ' . _DB_PREFIX_ . 'orders WHERE reference="' . $params['template_vars']['{order_name}'] . '" limit 1';
                $result = Db::getInstance()->ExecuteS($sql);
                $id_order = $result[0]['id_order'];
            }

            $order = new Order($id_order);
            $customer = new Customer($order->id_customer);

            if($customer->is_guest){
                $params['extra_template_vars']['{payment}'] = 'PayU, <a href="' . $this->context->link->getPageLink('index',true) .'index.php?controller=guest-tracking&email='.$customer->email.'&order_reference=' . $id_order . '#repayment">' . $this->l('Repay by PayU') . '</a>';
            }else{
                $params['extra_template_vars']['{payment}'] = 'PayU, <a href="' . $this->context->link->getPageLink('index',true) .'index.php?controller=order-detail&id_order=' . $id_order . '#repayment">' . $this->l('Repay by PayU') . '</a>';
            }
        }
    }

**Comment by regdos** [comment]
Poprawione w wersji https://github.com/PayU-EMEA/plugin_prestashop/releases/tag/v3.2.7
