### ISSUE TITLE
usage of deprecated hook

### ISSUE THREAD

**Issue by ghost** [PayU-EMEA/plugin_prestashop#312]
this hook got deprecated in prestashop 8.0
https://github.com/PayU-EMEA/plugin_prestashop/blob/1476d947babb3770f56835ae21d9fe4528de0095/payu/payu.php#L2031
it should be replaced with [this one](https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displaybackofficeheader/)

**Comment by regdos** [comment]
Fixed in 3.2.11
