### ISSUE TITLE
Problem z jednym zamówieniem

### ISSUE THREAD

**Issue by ChronoBrake** [PayU-EMEA/plugin_prestashop#317]
Witam, 
klient zrobił zamówienie z większą ilością produktów i wywala mu przy próbie ponowienia płatności błąd 504 (serwer coś mieli i nie może wyrobić się w odpowiednim czasie). Inne zamówienia działają, wszystko działa git poza tym jednym klientem. Używam wtyczki, że mogę zalogować się na konto klienta i faktycznie wywala mu 504. W trybie debug w logach nic się nie zapisuje. To chyba jakiś bug, ale nie wiem czy mogę coś podrzucić, aby pomóc w rozwiązaniu tego problemu. Proszę o pomoc. Pozdrawiam

**Comment by ChronoBrake** [comment]
ktoś tu udziela wsparcia?

**Comment by regdos** [comment]
Czy temat jest nadal aktualny?
