### ISSUE TITLE
Płatność kartą i obsługa tokenów wielorazowych

### ISSUE THREAD

**Issue by klapaucius4** [PayU-EMEA/plugin_prestashop#318]
Czy Państwa moduł wspiera w jakiś sposób obsługę tokenów wielorazowych?
Chodzi w skrócie o to, czy istnieje możliwość przypisywania tokenu do konta użytkownika, tak aby nie musiał on przy kolejnych płatnościach kartą wpisywać każdorazowo numeru karty kredytowej.

Czy moduł w jakiś sposób coś takiego umożliwia, czy trzeba by pisać własne customowe rozwiązanie aby coś takiego osiągnąć?

**Comment by regdos** [comment]
Aktualnie moduł obsługuje płatności kartą bez zapisu i aktualnie nie mamy w planach zmiany tego.
