### ISSUE TITLE
Płatność długo się ładuje a następnie zwraca internal error

### ISSUE THREAD

**Issue by JakubZojdzik** [PayU-EMEA/plugin_prestashop#320]
Po wpisaniu wszystkich wymaganych danych osobowych, adresu, wyborze sposobu płatności na PayU i wybraniu "Złóż zamówienie" strona wykonuje POST na /pl/module/payu/payment?payMethod=transfer, ładuje się przez długi czas a natępnie zwraca 500 internal error. Korzystam z prestashop 8.1.1, PHP 8.1.20, PayU plugin 3.2.15. Błąd występuje dla wszystkich sposobów płatności, w środowisku sandbox oraz produkcyjnym, dla wzytkich produktów. Wtyczka jest skonfigurowana dla kluczy konfiguracji punktu płatności REST API. Pomimo włączonego "debug mode" w prestashop, zwracany jest jedynie error 500 bez opisu.

**Comment by regdos** [comment]
Proszę sprawdzić katalog /var/log tam powinny być dodatkowe logi.
