### ISSUE TITLE
Problem z płatnościami

### ISSUE THREAD

**Issue by adamj240** [PayU-EMEA/plugin_prestashop#321]
Witam
Na sklepie Prestashop mam po płatności w większości przypadków komunikat "Płatność PAYU rozpoczęta" - klient dokonuje zakupu i opłaca normalnie. Tak jest praktycznie co drugie opłacone zamówienie. Czy to przez to że klient po wpłacie zamyka okno płatności?

**Comment by aidas-emersoft** [comment]
I have the same problem. Transaction in PayU account is complete, but the corresponding order in PrestaShop has "Płatność PAYU rozpoczęta" status - what could be the reason here?

**Comment by regdos** [comment]
Prawdopodobnie jest problem z odbieraniem notyfikacji. Proszę sprawdzić w panelu PayU jaka jest odpowiedź na notyfikacje. Przycisk "Pokaż raporty" w szczegółach transakcji.

**Comment by aidas-emersoft** [comment]
Problem solved. Reports were full of the following error: `code (ERROR): 403, Response: "error code: 1010"`, which means that the request wouldn't go through CloudFlare. If you are using CloudFlare you need to add a Browser Integrity Check bypassing rule:

![image](https://github.com/PayU-EMEA/plugin_prestashop/assets/53702044/4c5dad94-82cd-4eb2-94cc-5bf78c2bdf3f)
