### ISSUE TITLE
brak aktualizacji statusu transakcji po opłaceniu w panelu administracyjnym

### ISSUE THREAD

**Issue by fenomenologia** [PayU-EMEA/plugin_prestashop#325]
Od 24.01.2024 obserwujemy problem z aktualizacją statusów zamówień w panelu administracyjnym. Po dokonaniu zakupu i jego opłaceniu status zamówienia powinien się zmienić na "Płatność zaakceptowana" a tak się nie dzieje i cały czas jest status "Płatność PayU rozpoczęta"
Wersja wtyczki PayU v3.2.17 pobrana z github. Wersja Prestashop 1.7.6.4

**Comment by regdos** [comment]
Problem nie jest po stronie wtyczki tylko prawdopodobnie po stronie serwera a dokładnie oprogramowania WAF, które blokuje żądania od PayU. Proszę o kontakt z hostingodawcą i sprawdzenie czy nie są blokowane adresy z pul 185.68.12.0/24, 185.68.14.0/24

**Comment by fenomenologia** [comment]
Bardzo dziękuję za podpowiedź to oczywiście rozwiązało sprawę. Można usunąć ten ticket aby nie zaciemniał sekcji bo w sumie nic nie wnosi.
