### ISSUE TITLE
nowa opcja raty 5x0%

### ISSUE THREAD

**Issue by ChronoBrake** [PayU-EMEA/plugin_prestashop#329]
Witam, czy ta opcja jest wspierana przez ten moduł? Dodatkowo w dokumentacji nie widzę informacji na temat tego produktu. Jest gdzieś dostępna, aby we własnym zakresie ją dodać?

**Comment by mario-payu** [comment]
Płatności ratalne są jak najbardziej obsługiwane przez plugin wraz z ich promowaniem za pomocą widgetu na stronach koszyka, karty produktu oraz podsumowania zamówienia. Raty 5x0% to jeden z wariantów płatności ratalnych. W celu skorzystania z tej oferty prosimy o kontakt przez formularz: https://poland.payu.com/kontakt/ .
